name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dependencys
        run: sudo apt-get install -y shellcheck figlet screen expect gdb

      - name: Shellcheck
        run: shellcheck -x *.sh
