name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dependencys
        run: sudo apt-get install -y shellcheck figlet screen expect gdb

      - name: Shellcheck
        run: shellcheck -x *.sh

      - name: Minimal setup
        run: |
          touch autoexec.cfg
          {
            echo "git_root=/home/$USER"
            echo "gitpath_mod=/home/$USER/teeworlds"
            echo "gitpath_log=/home/$USER/.teeworlds/dumps/TeeworldsLogs"
            echo "server_name=test-srv"
            echo "editor=touch"
          } > server.cnf
          mkdir -p /home/$USER/.teeworlds/dumps/TeeworldsLogs/test-srv/logs

      - name: Unit tests
        run: ./lib/run_tests.sh

